[server]
port = 8501
headless = true
maxUploadSize = 500
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0068c9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[client]
showSidebarNavigation = false
toolbarMode = "minimal"
